/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import client.ChatClient;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.apache.maven.shared.utils.StringUtils;

/**
 *
 * @author PC
 */
class ChatPrivata extends JFrame {

    //Nome dell'utente
    String nome;
    boolean log = false;
    /**
     * Creates new form Chatting
     */
    public ChatPrivata(String nomechat){
        super("Chat");//Il titolo della finestra
        setSize(350, 400);//Setta la grandezza della finestra
        setLocation(400, 200);//Setta la posizione della finestra nello schermo
        setDefaultCloseOperation(EXIT_ON_CLOSE);//Permette di chiudersi tutto il programma
        setVisible(true);
        initComponents();
        Messaggi.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        chat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Chattare = new javax.swing.JTextArea();
        ButtonInvio = new javax.swing.JButton();
        Messaggi = new javax.swing.JTextField();
        NomeUtente = new javax.swing.JTextField();
        Okbutton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(51, 255, 0));

        chat.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        chat.setText("Chat");
        chat.setAlignmentX(0.5F);
        chat.setMaximumSize(new java.awt.Dimension(23, 14));

        Chattare.setColumns(20);
        Chattare.setRows(5);
        Chattare.setText("Buongiornissimo");
        jScrollPane1.setViewportView(Chattare);

        ButtonInvio.setText("Invia");
        ButtonInvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInvioActionPerformed(evt);
            }
        });

        Messaggi.setText("Scrivi il tuo messaggio");
        Messaggi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MessaggiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MessaggiFocusLost(evt);
            }
        });
        Messaggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessaggiActionPerformed(evt);
            }
        });

        NomeUtente.setBackground(new java.awt.Color(204, 204, 255));
        NomeUtente.setText("Nome");
        NomeUtente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NomeUtenteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NomeUtenteFocusLost(evt);
            }
        });
        NomeUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeUtenteActionPerformed(evt);
            }
        });

        Okbutton.setText("Ok");
        Okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NomeUtente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Okbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Messaggi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonInvio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeUtente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Okbutton))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonInvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Messaggi))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonInvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInvioActionPerformed
                ChatClient client = new ChatClient("127.0.0.1", 8818, nome);
                String[] tokens = StringUtils.split(Messaggi.getText());
                String hashtag = tokens[0];
                String utente = tokens[1];
                      if(tokens[0] == "#"){
                        try {
                            log = client.chatPrivata(hashtag, utente);
                             if(log){
                                   Chattare.setText(Chattare.getText() + "\n" + "Nuova chat per te : " + utente);
                                   ChatPrivata chatpr = new ChatPrivata(utente);
                             }else{
                                   Chattare.setText(Chattare.getText() + "\n" + "Non presente : " + utente);
                             }} catch (IOException ex) {
                                 Logger.getLogger(Chatting.class.getName()).log(Level.SEVERE, null, ex);
                                 }
                      }else{
                          Chattare.setText(Chattare.getText() + "\n" + client.Comunica(nome, Messaggi.getText()));
                            }
    }//GEN-LAST:event_ButtonInvioActionPerformed

    private void MessaggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessaggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MessaggiActionPerformed

    private void NomeUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeUtenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeUtenteActionPerformed

    private void NomeUtenteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NomeUtenteFocusGained
        if(NomeUtente.getText().equals("Nome")){
            NomeUtente.setText("");
        }
        NomeUtente.setForeground(Color.YELLOW);
    }//GEN-LAST:event_NomeUtenteFocusGained

    private void NomeUtenteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NomeUtenteFocusLost
        if(NomeUtente.getText().equals("")){
            NomeUtente.setText("Nome");
        }
        NomeUtente.setForeground(new Color(102, 102, 255));
    }//GEN-LAST:event_NomeUtenteFocusLost

    private void OkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkbuttonActionPerformed
        NomeUtente.setEnabled(false);
        Messaggi.setEnabled(true);
        nome = NomeUtente.getText();
        ChatClient client = new ChatClient("127.168.0.1", 8818, nome);
        if(!client.Connetti()){
            System.err.println("Connessione fallita");
        }else{
                Chattare.setText("Connessione riuscita con successo");
                Chattare.setText(this +"\n" + "Scrivi quello che vuoi questa chat è pubblica");
        }
    }//GEN-LAST:event_OkbuttonActionPerformed

    private void MessaggiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MessaggiFocusGained
        if(NomeUtente.getText().equals("Scrivi il tuo messaggio")){
            NomeUtente.setText("");
        }
        NomeUtente.setForeground(Color.YELLOW);        
    }//GEN-LAST:event_MessaggiFocusGained

    private void MessaggiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MessaggiFocusLost
        if(NomeUtente.getText().equals("")){
            NomeUtente.setText("");
        }
        NomeUtente.setForeground(new Color(102, 102, 255));               
    }//GEN-LAST:event_MessaggiFocusLost
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonInvio;
    private javax.swing.JTextArea Chattare;
    private javax.swing.JTextField Messaggi;
    private javax.swing.JTextField NomeUtente;
    private javax.swing.JButton Okbutton;
    private javax.swing.JLabel chat;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}